### PR TITLE
Chunkify and winter cleanup

### PR DESCRIPTION
**Pull request by norman784**
Notable changes:

- Working on a Chunkify trait to make easy to implement your own chunk and still benefit from the library
- Removed some unneeded dependencies
- Removed gaiku-2d, I'm not sure if I want or need to implement this library
- rustfmt/clippy
- maybe some other stuff I forgot about

### CODE REVIEW

**Comment by norman784** [comment]
@QuantumEntangledAndy want you check this PR and see how it affects your project? Also comments are welcome.

**Comment by QuantumEntangledAndy** [comment]
This seems to have reverted my changes on the voxel baker, was this intentional? I believe that this will stop the shading and the texturing from working.

Not sure how the Chunkify trait will effect my project though, the interesting parts all happen in the baking.

**Comment by norman784** [comment]
> This seems to have reverted my changes on the voxel baker, was this intentional?

Was not, I will check it out what happened.


> Not sure how the Chunkify trait will effect my project though, the interesting parts all happen in the baking.

Cool

**Comment by QuantumEntangledAndy** [comment]
So it occurs to me that with a traited chunk I can plug my noise function's `get` method straight into the output of the traits `get` method. Since this noise function is continuous and defined over all of space the neighbors part of your code elsewhere can be completely skipped if the baker just polls the value outside the size of the chunk.

Using a noise function also mostly makes `set` irrelevant since it cannot actually be changed like that. Perhaps `set` and `get` should be in different traits?

**Comment by norman784** [comment]
Can you open a PR with your suggestion?

edit: this PR is closed, so you might check the #13, has the same changes but isn't messed up

**Pull request closed without merging**
