### PR TITLE
Add padding to atlas tiles (remerge)

### PR DESCRIPTION
**Pull request by norman784**
Merge changes from #34 into master

### CODE REVIEW

**Comment by QuantumEntangledAndy** [comment]
I see you fixed the tests already. I had a fixed test merge as well as some additional tests too ready to merge but saw that it wasn't mergable when I tried to make the PR :)

**Comment by QuantumEntangledAndy** [comment]
I have a PR that fixes the issues here and the and adds some more tests. It will be based and merged into this branch

**Comment by QuantumEntangledAndy** [comment]
Made please apply #38 before this one

**Comment by norman784** [comment]
Thanks, will do that.

**Pull request merged**
