### PR TITLE
Add padding to the atlas tiles

### PR DESCRIPTION
**Pull request by norman784**
This seems to fix https://github.com/norman784/gaiku/pull/23#issuecomment-761853576 and https://github.com/norman784/gaiku/issues/27#issuecomment-761829133

### CODE REVIEW

**Comment by QuantumEntangledAndy** [comment]
I see yes the artifacts were probably caused by rounding error moving the closest pixel to the one just outside side of the tile.

We could also have fixed this by added a 1 pixel border with color bleeding into this border.

**Comment by norman784** [comment]
So far the ellipsis 1e-5 seems to work in bevy and blender, could you check in amethyst?

> We could also have fixed this by added a 1 pixel border with color bleeding into this border.

About this I'm not sure how to tackle the issue when we start using textures instead of solid colors, maybe stretch by one pixel the edges?

**Comment by QuantumEntangledAndy** [comment]
I was thinking

- at init increase texture size by +2 per tile per dimension
- adjust start xy to accomidate the extra pixels
- When using the set pixels:
  - if pixel is being set at the edges copy pixel to the neighbouring border padding

It is not perfect but I suspect it will reduce the visibilty of artifacts.

I also expect your 1e-5 to help with textures too as long as we always work with whole square faces

**Comment by QuantumEntangledAndy** [comment]
Without this PR:

Screenshot 2021-01-19 at 10 32 01

With this PR:

Screenshot 2021-01-19 at 11 54 25

**Comment by QuantumEntangledAndy** [comment]
From the pink in the tree at the bottom right I think we are still getting color bleeding from somewhere

**Comment by QuantumEntangledAndy** [comment]
I increased the pad size to 5e-2 and that tree is still pinkish:

- pad: 5e-2

Screenshot 2021-01-19 at 12 22 18

**Comment by QuantumEntangledAndy** [comment]
I have gone and added border pixels too please see  #34

**Pull request merged**
