### PR TITLE
Reorganize crates (breaking change)

### PR DESCRIPTION
**Pull request by norman784**

### CODE REVIEW

**Comment by norman784** [comment]
@QuantumEntangledAndy I want to hear what do you think about this PR, this change isn't definitive, I'm exploring and checking what's easy to use/maintain. For example using feature flags can quickly become a nightmare if you have too many of them. We can still expose them in the `gaiku` (this just re-exports all the crates) crate but you can freely use the `gaiku_*` crates if you don't like feature flags.

**Comment by QuantumEntangledAndy** [comment]
This is quite similar to how amethyst does it so at least game engine Devs should be used to it. I like the seperate creates with the re-exports from the main. But I think features should be orthogonal (dosent conflict with each other). I know this is difficult because amethyst has non orthogonal features for their renderer not sure what bevy does. Should try to set up features where possible in a way that they are not mutually exclusive. If they are mutually exclusive such as the amethyst and bevy integration maybing having them as a seperate creates and not part of the main re-export. 

Having orthogonal features means we can do something like 

cargo test --all-features

And test all the features at once for the main gaiku create.

**Comment by norman784** [comment]
That makes sense, if we do that then the crates need to be removed from the workspace or just remove the dependencies in the main crate?

**Comment by QuantumEntangledAndy** [comment]
I think we can leave them in the workspace but when testing and building we build from the main `gaiku` crate with `--all-features` not the workspace. This should test all of the orthogonal creates because they are re-exports.

We then do separate tests on the non orthogonal integrations. This will let us have amethyst and bevy despite their conflicting requirements.

**Comment by norman784** [comment]
I will merge as is it now, but there are few missing things:

- Run clippy, fmt and test for the integrations
- Will be cool to rework the examples and maybe use the integrations in them instead of just output obj files.

**Comment by QuantumEntangledAndy** [comment]
Question; is there anyway to access gaiku_common from the `gaiku` crate? I can only seem to access it if I import `gaiku_common` directly.

**Comment by norman784** [comment]
I forgot to expose it, it should be re-exported.

**Pull request merged**
