### PR TITLE
Playing with textures

### PR DESCRIPTION
**Pull request by norman784**
Notable changes:

- Added support for textures.
- Split Chunkify into different other traits (Sizable, Positionable, Boxify).
- Added MeshBuilder (internally uses an octree implementation, I think is faster than the previous implementation).
- Changed whenever possible the use of Vec3/Vector3 for [f32; 3] (it makes easy to convert into the needed type in the user land), same for other Vec(n) types.
- Improved amethyst ergonomics, implemented into for MeshData and TextyreData.
- Removed support of colors (now you can add it by creating a custom chunk and implementing the required traits by the baker/file format).
- Removed unneeded dependencies.

### CODE REVIEW

**Comment by QuantumEntangledAndy** [comment]
Anything fun happening here? I am working on background loading in amethyst it is quite ok. At the moment I need to generate the mesh and texture completely before conversion to amethyst since during texture generation the UVs of the mesh are edited. It might be nice if the UVs were deterministic at mesh creation so that the two processes could be independent (amethyst has its own background loading methods for mesh and texture but only if the processes are seperable afaik). But that might be too much cognitive load.

**Comment by norman784** [comment]
> Anything fun happening here?

I'm doing some changes interesting changes (I added brief description in the PR), I changed the base branch of this PR with #13 so you can see clearly the changes I'm doing.

The idea here is to implement useful features, like texture support in replacement of colors, I think colors where cool but in real projects you will not use them. So I'm building the foundations to support textures and texture atlas, I think for terrains this approach suits quite well, but I'm open to sugestions because I have not a clear roadmap yet about this one.

When I get this implemented and working, we can iterate to fit your use case.

> It might be nice if the UVs were deterministic

What's your suggestion here?

**Comment by QuantumEntangledAndy** [comment]
Well there a few different way to define UV at mesh creation.

All voxels unique: Since we add faces in a fixed order and those faces are for one voxel at a time, we could add map for voxel 0 in position 0 of the UV map for voxel 1 in position 1 and so on.

All planes: we could also look for contious planes and make islands for those.

Any method really we just need to pick something.

**Comment by norman784** [comment]
What architecture do you think fits better your project, texture atlas or texture array? Because with my current approach I didn't take into account the faces, I have just one texture per block (and we want at least 3 faces, top, bottom and side).

It seems that I need to build a pet project to iterate over this idea, right now I don't have any.

**Review by norman784 — COMMENTED** [review]
@QuantumEntangledAndy do you think that [this change](https://github.com/norman784/gaiku/pull/14/commits/049c32a43087616d6c17b21f6e03e534ac810399) works for your use case? I added a WIP SparseChunk that resembles (maybe?) to your described use case (except that I didn't include any noise function inside, maybe we can build one with noise in the 3d examples, just to maintain the dependencies from the library as minimum as possible).

Let me know what you think and if there is any change that you will need.

**Comment by norman784** [comment]
There's still some issues I need to resolve, right now some `MeshBuilderData` fails to insert into the `MeshBuilderOctree`, so the examples/benchmarks might not work yet.

**Comment by norman784** [comment]
@QuantumEntangledAndy also there are improvements (I think) for the gaiku-amethyst crate, let me know if this change is good for you or you need any other change, if not we can open a PR based on this one and work there.

There's only one issue preventing me to merge this and it's related to my previous comment.

**Comment by QuantumEntangledAndy** [comment]
| do you think that this change works for your use case? I added a WIP SparseChunk that resembles (maybe?) to your described use case

Its a nice addition to the library but not quite right for my tree example because: Internally the tree has roots at (0,0,0) and can grow in the negative direction, but at bake and render time its all shifted to the positive domain and the position update to keep it in the same place. I think `Chunk` and `SparseChunk` should be enough for most use cases anything beyond that like in my tree should be handled in user land with `Chunkify`.

| also there are improvements (I think) for the gaiku-amethyst crate

I will have a look currently I am rebaseing my project on your latest changes (from merging this PR) and trying to get Chunkify to work. The last merge seemed to have broken things will open issue if I cannot get it up and running.

| maybe we can build one with noise in the 3d examples

Maybe it would be a good idea to add some examples like that and maybe an example tree too.

**Pull request merged**
