### PR TITLE
Tests and benches

### PR DESCRIPTION
**Pull request by QuantumEntangledAndy**
This should get all the tests and benches working for the recent changes.

I have gone and used the `resolver=2` feature resolver so that `amethyst/metal` or vulkan dependencies auto  enable based on the os. This is a new feature that has only recently been stabalised so may need to use the latest rust. Rust stablise PR is [here](https://github.com/rust-lang/cargo/pull/8997)

### CODE REVIEW

**Comment by norman784** [comment]
Thanks for the fixes.

I have one change that like to ask you, because you splitted the benches from single entry point to individual ones, maybe should remove the benchmarks module and move the code to each entry point.

**Comment by QuantumEntangledAndy** [comment]
Sure I was debating that with myself but thought I'd try to keep the diff to a minimal

**Comment by QuantumEntangledAndy** [comment]
I have made the change and I am running the benches now to make sure I didn't break anything

**Comment by QuantumEntangledAndy** [comment]
Ok Done!

**Comment by QuantumEntangledAndy** [comment]
By the way the whole reason I did this was because I wanted to test the benches.

I had a chunk where depth, width and height were expensive functions calls and the voxel baker was calling them often as you can see here:


```rust
    let x_limit = chunk.width() as usize - 1;
    let y_limit = chunk.height() as usize - 1;
    let z_limit = chunk.depth() as usize - 1;

    for x in 0..chunk.width() as usize {
      for y in 0..chunk.height() as usize {
        for z in 0..chunk.depth() as usize {
```

For large chunks (600 voxels per dimension) the functions `depth` `width` and `height` will get called millions of times and I wanted to see if this can be improved by caching the value. That meant using the benches

**Comment by QuantumEntangledAndy** [comment]
I am going to add another bench mark using a chunk with a 3d checkerboard:

```
0 1 0 1 0
1 0 1 0 1
0 1 0 1 0
```

This should resemble a chunk that requires maximum work to bake as their are 6 unique edges per vertex.

**Pull request merged**
