### PR TITLE
Padding pixels

### PR DESCRIPTION
**Pull request by QuantumEntangledAndy**
This adds border padding pixels in addition to the 1e-5 rounding error you have added:

- Before:

Screenshot 2021-01-19 at 12 22 18

- After 

Screenshot 2021-01-19 at 14 58 10

### CODE REVIEW

**Comment by QuantumEntangledAndy** [comment]
Its an improvment but I am still not sure about some of those line, I will try exporting the image as a png and make sure it is behaving

**Comment by norman784** [comment]
You can use blender to visualize how the uvs are positioned in the texture.

**Comment by QuantumEntangledAndy** [comment]
That's a good idea just need to export the chunk too. If only it didn't take 30 mins to compile on my little mac....

**Comment by QuantumEntangledAndy** [comment]
Screenshot 2021-01-19 at 16 24 49

This is the generated tile map, it seems that my padding fill calc is missing the upper right and bottom left

**Comment by QuantumEntangledAndy** [comment]
Also can we make export to obj part of the chunk just to ease the process

**Comment by QuantumEntangledAndy** [comment]
And fixed the padding to get:

Screenshot 2021-01-19 at 17 22 21

:)

**Comment by QuantumEntangledAndy** [comment]
UVs in blender look correct:

Screenshot 2021-01-19 at 17 31 02

But it seems that in blender the v axis is flipped

**Comment by QuantumEntangledAndy** [comment]
Flipping the v coordinate in blender makes this:

Screenshot 2021-01-19 at 17 37 30

**Comment by QuantumEntangledAndy** [comment]
For some reason we cannot set the last pixel in the image

Screenshot 2021-01-19 at 17 31 02

**Comment by QuantumEntangledAndy** [comment]
This line here:

https://github.com/norman784/gaiku/blob/6fc73cd75308847abf54257790bb304119af24ea/gaiku-common/src/texture.rs#L171-L173

Should read:

```rust
  fn set_pixel_at_index(&mut self, index: usize, data: [u8; 4]) {
    if index <= self.data.len() - 4 {
      for (i, value) in data.iter().enumerate() {
        self.data[index + i] = *value;
      }
    }
  }
```

Consider this math to test it

- For a 48*48 pixel image:
- There are 0..47 x and y pixels by index
- We want to set the pixel at 47,47
- The index for this pixel is `x * 4 + width * y * 4 = 47*4+48*47*4 = 9212`
- The length of the texture bytes is `width*width*4 = 48*48*4 = 9216`
- Subtract 4 from the length is: `9216 - 4 = 9212`
- The index does not fulfil this condition
```
    if index < self.data.len() - 4 {
```
So the last pixel is unsetable

**Comment by QuantumEntangledAndy** [comment]
Ready for your testing and approval

**Comment by QuantumEntangledAndy** [comment]
This is another issue for elsewhere just thought I'd mention it here:

There's an artifact here:

Screenshot 2021-01-19 at 18 10 12

Which is caused because there are two verticies at this point:

Screenshot 2021-01-19 at 18 10 32


It seems the deduplication step of the meshing algorithm is not tolerant enough

**Comment by QuantumEntangledAndy** [comment]
I think it is caused here, which I was thinking of when I wrote this part:

```rust
cx - sx * (1. + EPSILON),
cy - sy * (1. + EPSILON),
cz - sz * (1. + EPSILON),
```

- When checking for duplicates `sx = 1e-5`
- `sx * (1. + EPSILON) = 1e-5*( 1+1e-5) = 1.00001e-05` which is 6sf so it is fine`
- `cx` is the coordinate center which could be anything lets say `123.0`
- `cx + 1.00001e-05 = 123.0 + 1.00001e-05 = 123.00001` Which is 8 sf too many sf for f32
- Truncating previous to 6sf we get `123.000` which is equivalent boundary size of `0.`
- Which means if there is any rounding error in the coordinate it won't be treated as duplicate

**Comment by QuantumEntangledAndy** [comment]
Shall I fix that in this PR or do you want me to open a new one?

**Comment by norman784** [comment]
> Shall I fix that in this PR or do you want me to open a new one?

I would like to keep as small as possible each PR when possible, so it's easier to review. If possible open another PR with the fix.

**Comment by QuantumEntangledAndy** [comment]
I see then I'll leave this one as it is for now. Please review it. Sorry if the amethyst stuff gets in the way of the review.

**Comment by QuantumEntangledAndy** [comment]
To reduce clutter I took out the amethyst changes and added a few more test that check that the padding is working and that every pixel is setable.

**Comment by norman784** [comment]
I ran the amethyst example in another machine and it looks awesome!

**Comment by QuantumEntangledAndy** [comment]
This PR was based off and merged into the branch `norman784:add-padding-to-atlas-tiles` not `master`. Since `norman784:add-padding-to-atlas-tiles` was already merged before this PR these commits are not in master :(

**Comment by QuantumEntangledAndy** [comment]
p.s. why dosen't amethyst run on your linux box? Is it to do with the vulkan drivers? Just curious for future release issues

**Comment by norman784** [comment]
> This PR was based off and merged into the branch `norman784:add-padding-to-atlas-tiles` not `master`. Since `norman784:add-padding-to-atlas-tiles` was already merged before this PR these commits are not in master :(

My bad, I'll merge it with #37 in a few hours.

> p.s. why dosen't amethyst run on your linux box? Is it to do with the vulkan drivers? Just curious for future release issues

I don't know what's the issue, this is the cash log.

```
thread 'main' panicked at 'attempted to leave type `platform::platform::x11::util::input::PointerState` uninitialized, which is invalid', /home/norman784/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:659:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[ERROR][rendy_resource::escape] Terminal must be dropped after all `Escape`s
[ERROR][rendy_resource::escape] Terminal must be dropped after all `Escape`s
[ERROR][rendy_resource::escape] Terminal must be dropped after all `Escape`s
[ERROR][rendy_resource::escape] Terminal must be dropped after all `Escape`s
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(1048576) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(131072) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(28928) is still used
[ERROR][rendy_memory::allocator::dedicated] Not all allocation from DedicatedAllocator was freed
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(262144) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(1048576) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(256) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(2048) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(16384) is still used
[ERROR][rendy_memory::allocator::dynamic] Memory leak: SizeEntry(131072) is still used
[ERROR][rendy_descriptor::allocator] Not all descriptor sets were deallocated
[ERROR][rendy_descriptor::allocator] Descriptor pool is still in use during allocator disposal. DescriptorPool { size: 64, free: 62, freed: 0 }
[ERROR][rendy_descriptor::allocator] Not all descriptor sets were deallocated
[ERROR][rendy_descriptor::allocator] Descriptor pool is still in use during allocator disposal. DescriptorPool { size: 64, free: 62, freed: 0 }
[ERROR][rendy_descriptor::allocator] Not all descriptor sets were deallocated
[ERROR][rendy_descriptor::allocator] Descriptor pool is still in use during allocator disposal. DescriptorPool { size: 64, free: 63, freed: 0 }
[ERROR][rendy_descriptor::allocator] Not all descriptor sets were deallocated
[ERROR][rendy_descriptor::allocator] Descriptor pool is still in use during allocator disposal. DescriptorPool { size: 64, free: 62, freed: 0 }
[ERROR][rendy_descriptor::allocator] Not all descriptor sets were deallocated
[ERROR][rendy_descriptor::allocator] Descriptor pool is still in use during allocator disposal. DescriptorPool { size: 64, free: 0, freed: 0 }
[ERROR][rendy_descriptor::allocator] Descriptor pool is still in use during allocator disposal. DescriptorPool { size: 64, free: 0, freed: 0 }
[ERROR][rendy_descriptor::allocator] Descriptor pool is still in use during allocator disposal. DescriptorPool { size: 128, free: 125, freed: 0 }
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
[ERROR][rendy_resource::escape] `Escape` was dropped after a `Terminal`?
```

I don't think is a vulkan issue, I can run without issue vulkan games and bevy I believe uses vulkan (via webgpu) too and runs without issues.

**Comment by QuantumEntangledAndy** [comment]
I think your issue is in https://github.com/norman784/gaiku/pull/34 allready solved then just have to wait for it to land in stable :)

**Pull request merged**
