### PR TITLE
Add vertex normals to voxel baker

### PR DESCRIPTION
**Pull request by QuantumEntangledAndy**
This just adds vertex normals to the voxel baker. Needed it for my own project and thought I'd share :)

p.s. sorry for my crude rust coding

p.p.s I have this working in amethyst would you like me to PR something to the amethyst part of the code base?

### CODE REVIEW

**Review by norman784 — APPROVED** [review]
Cool, I didn't work in this project for a while, but maybe I should continue working on it. Thanks for the contribution, it is much appreciated.

I just gave up a quick look and seems fine.

**Comment by QuantumEntangledAndy** [comment]
The normals here are not quite right at the sharp corners and shades oddly when rendering in amethyst. The root cause is that we need two normals at the corner. To solve this we should duplicate the vertices if Angle between normals differs more than some value (e.g. 45 degrees). We should also duplicate the vertices if the color differs since you can't have two vertexes with the same colour.

I have another set of changes that makes more far reaching changes that does all this and then creates UV and textures so that it's in colour.

It also does better hashing of the coordinates so that it's not strings anymore.

**Comment by QuantumEntangledAndy** [comment]
When I get some time I'll work up a PR with these chances too. But it's not really optimised as my rust foo is pretty basic. I'm sure there's a fancy iter mapping I can do for something of my transformations.

**Comment by norman784** [comment]
> The normals here are not quite right at the sharp corners and shades oddly when rendering in amethyst. The root cause is that we need two normals at the corner. To solve this we should duplicate the vertices if Angle between normals differs more than some value (e.g. 45 degrees). We should also duplicate the vertices if the color differs since you can't have two vertexes with the same colour.

About this one, one trick is to read the data from the adjacent chunk and use it to calculate the normal, but exclude from the mesh generation, I have some idea how could it be implemented, but never worked on get that feature done.

> I have another set of changes that makes more far reaching changes that does all this and then creates UV and textures so that it's in colour.

Love to see this change.

> It also does better hashing of the coordinates so that it's not strings anymore.

That sounds cool, at the time I started with this I didn't got any better (or rather easier way) to implement it.

**Comment by norman784** [comment]
> When I get some time I'll work up a PR with these chances too. But it's not really optimised as my rust foo is pretty basic. I'm sure there's a fancy iter mapping I can do for something of my transformations.

I'm not too concerned with optimization right now, because this is a learning project for me, I believe that it must work first to optimize it, also there are a lot of features that are still missing and to get there a lot of stuff will change to get it there.

**Comment by QuantumEntangledAndy** [comment]
> About this one, one trick is to read the data from the adjacent chunk and use it to calculate the normal, but exclude from the mesh generation, I have some idea how could it be implemented, but never worked on get that feature done.
> 

Not quite what I mean. Im not talking about the normals at the chunk boundaries. Let's image a cube with no chunks to the side. The lower vertices have vertex normals that are the average of the down and side. When light comes from up and to the side it won't light the bottom vertices because they are pointing mostly downwards. This is correct for the underside but because those verities are also part of the side too the the lower half of the sides are unlit.

This is correct if we want smooth shading but since we have cubes you'd expect something more rigid and for the whole side of the cube to be lit.

**Pull request merged**
